name: CI

on:
  push:
    branches: [ devel3 ]
  pull_request:
    branches: [ devel3 ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/fnalacceleratormodeling/synergia2-ubuntu-container:main
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: CMake
      run: |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DKokkos_ENABLE_OPENMP=on -DBUILD_PYTHON_BINDINGS=off -DUSE_EXTERNAL_KOKKOS=on

    - name: Build
      # Build your program with the given configuration
      run: |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload the build output
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: |
          ${{github.workspace}}/build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/fnalacceleratormodeling/synergia2-ubuntu-container:main
  
    steps:
    - name: Download the build output
      uses: actions/download-artifact@v2
      with:
        name: build-output
    - name: ctest
    # Execute tests defined by the CMake configuration.
      run:  |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        cd ${{github.workspace}}/build
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure
