name: CI

on:
  push:
    branches: [ devel3 ]
  pull_request:
    branches: [ devel3 ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/fnalacceleratormodeling/synergia2-ubuntu-container:main
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: CMake
      run: |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DKokkos_ENABLE_OPENMP=on -DBUILD_PYTHON_BINDINGS=off

    - name: Build
      # Build your program with the given configuration
      run: |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: ctest
      # Execute tests defined by the CMake configuration.
      run:  |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        ctest -C ${{env.BUILD_TYPE}} --test-dir ${{github.workspace}}/build --output-on-failure
