name: CI:gcc

on:
  push:
    branches: [ devel3 ]
  pull_request:
    branches: [ devel3 ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fnalacceleratormodeling/synergia2-containers/ubuntu-gcc:main
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: CMake
      run: |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DBUILD_PYTHON_BINDINGS=on -DPYTHON_EXECUTABLE=$(which python3.9) \
          -DUSE_EXTERNAL_KOKKOS=on -GNinja

    - name: Build
      # Build your program with the given configuration
      run: |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2

    - name: ctest
    # Execute tests defined by the CMake configuration.
      run:  |
        . /etc/profile.d/z10_spack_environment.sh 
        . /opt/view/setvars.sh
        cd ${{github.workspace}}/build
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure
