name: CI:macOS-gcc

on:
  push:
    branches: [ devel3 ]
  pull_request:
    branches: [ devel3 ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-and-test:
    runs-on: macos-latest
  
    steps:
    - name: Cancel Previous runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
     
    - name: Dependencies
      run: |
        brew install gcc gsl hdf5 fftw libomp numpy mpi4py pybind11 ninja
        python3 -m venv --system-site-packages ${{github.workspace}}/synergia-env
        source ${{github.workspace}}/synergia-env/bin/activate
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest pyparsing matplotlib h5py

    - name: CMake
      run: |
        source ${{github.workspace}}/synergia-env/bin/activate
        CC=gcc-11 CXX=g++-11 cmake -B ${{github.workspace}}/build \
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DKokkos_ENABLE_OPENMP=on \
        -DBUILD_PYTHON_BINDINGS=on -GNinja

    - name: Build
      # Build your program with the given configuration
      run: |
        source ${{github.workspace}}/synergia-env/bin/activate
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: ctest
    # Execute tests defined by the CMake configuration.
      run:  |
        cd ${{github.workspace}}/build
        source ${{github.workspace}}/synergia-env/bin/activate
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure
