name: CI:ubuntu-clang

on:
  workflow_dispatch:
    inputs:
      debug_cmake_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      debug_tests_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  push:
    branches: [ devel3 ]
    paths-ignore:
      - 'wiki/**'
  pull_request:
    branches: [ devel3 ]
    paths-ignore:
      - 'wiki/**'

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fnalacceleratormodeling/synergia2-containers/ubuntu-clang:main
  
    steps:
    - name: Cancel Previous runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    # Debug: checkpoint at which to open tmate session
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.debug_cmake_enabled }}
      with:
        sudo: false


    - name: CMake
      run: |
        lscpu
        . /etc/profile.d/z10_spack_environment.sh 
        CC=/usr/bin/clang-14 CXX=/usr/bin/clang++-14 LDFLAGS="-fuse-ld=lld" cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
          -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install \
          -DBUILD_PYTHON_BINDINGS=on -DPYTHON_EXECUTABLE=$(which python3.9) \
          -DUSE_EXTERNAL_KOKKOS=off -GNinja

    - name: build
      # build synergia2
      run: |
        . /etc/profile.d/z10_spack_environment.sh 
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2 

    - name: install
      # install synergia2
      run: |
        . /etc/profile.d/z10_spack_environment.sh 
        cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # Debug: checkpoint at which to open tmate session
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{github.event_name == 'workflow_dispatch' && github.event.inputs.debug_tests_enabled }}
      with:
        sudo: false

    - name: ctest
    # Execute tests defined by the CMake configuration.
      run:  |
        . /etc/profile.d/z10_spack_environment.sh 
        cd ${{github.workspace}}/build
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    # Debug: checkpoint at which to open tmate session
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    #  with:
    #    sudo: false
        
    - name: run-fodopy
    # Run the fodopy example from README.
      run:  |
        . /etc/profile.d/z10_spack_environment.sh 
        export SYNINSTALL=${{github.workspace}}/install
        export LD_LIBRARY_PATH=${SYNINSTALL}/lib:${SYNINSTALL}/lib64:\${LD_LIBRARY_PATH}
        export PYTHONPATH=${SYNINSTALL}/lib:${SYNINSTALL}/lib/python3.9/site-packages:\${PYTHONPATH}
        cd ${{github.workspace}}/build/examples/fodo
        mpirun -np 1 python3.9 fodo_readme.py
